## Importing the necessary modules

In [20]:
from json import loads
from random import choice, shuffle
from string import punctuation
from keras import Sequential
from keras.layers import Dense, Dropout, LeakyReLU, Softmax, Input
from keras.optimizers import Adam
from nltk import word_tokenize
from nltk.stem import WordNetLemmatizer
from numpy import array
'''
nltk.download("punkt")
nltk.download("wordnet")
nltk.download('omw-1.4')
'''


'\nnltk.download("punkt")\nnltk.download("wordnet")\nnltk.download(\'omw-1.4\')\n'

## Loading the dataset

In [21]:
data = loads(open("dataset/intents.json", encoding="utf-8").read())


## Using NLP to clean the data

In [22]:
lemmatizer = WordNetLemmatizer()

# Each list to create
words = [] # tokenized words of sentences in patterns
classes = [] # tags
doc_X = [] # patterns
doc_y = [] # tags ocurring number of times wrt patterns

'''Looping through all the intents and tokenizing each patterns and
appending tokens to words, patterns and associated tag to
their associated list'''
for intent in data["intents"]:
    for pattern in intent["patterns"]:
        tokens = word_tokenize(pattern)
        words.extend(tokens)
        doc_X.append(pattern)
        doc_y.append(intent["tag"])
    # add the tag to the classes if it's not there already
    if intent["tag"] not in classes:
        classes.append(intent["tag"])


In [23]:
# lemmatizing all the words in the vocab and
# converting them to lowercase if the words
# don't appear in punctuation
words = [lemmatizer.lemmatize(word.lower()) for word in words if word not in punctuation]


In [24]:
'''sorting the vocab and classes in alphabetical order
and taking the set to ensure no duplicates occur'''
words = sorted(set(words))
classes = sorted(set(classes))


In [25]:
print("lenght of words: ", len(words))
print("length of doc_X", len(doc_X))
print("length of doc_y", len(doc_y))
print("length of classes", len(classes))


lenght of words:  137
length of doc_X 208
length of doc_y 208
length of classes 54


## Creating training and test sets

In [26]:
# list for training data
training = []

# creating the bag of words model
for idx, doc in enumerate(doc_X):
    bow = []
    # lemmatizing the sentence and converting to lowercase
    text = lemmatizer.lemmatize(doc.lower())
    for word in words:
        # one hot encoding the words if they appear in the text
        if word in text:
            bow.append(1)
        else:
            bow.append(0)
    output_row = [0] * len(classes)
    # marking the index of class that the current pattern is associated to as 1
    output_row[classes.index(doc_y[idx])] = 1
    # adding the one hot encoded BoW and associated classes to training
    training.append([bow, output_row])


In [27]:
# shuffling the data and convert it to a numpy array
shuffle(training)
training = array(training, dtype=object)


In [28]:
# splitting the features and target labels
train_X = array(list(training[:, 0])) # features
train_y = array(list(training[:, 1])) # target labels


In [29]:
print(train_X)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [30]:
print(train_y)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [31]:
print(f"Shape of train_X: {train_X.shape}")
print(f"Shape of train_y: {train_y.shape}")


Shape of train_X: (208, 137)
Shape of train_y: (208, 54)


# Building deep learning model

In [32]:
# defining some parameters
input_shape = (len(train_X[0]),)
output_shape = len(train_y[0])
print("input_shape: ", input_shape)
print("output_shape: ", output_shape)


input_shape:  (137,)
output_shape:  54


In [33]:
# defining the model
model = Sequential(name="Anuradha")
model.add(Input(shape=input_shape, name="input_layer"))
model.add(Dense(256, activation=LeakyReLU(alpha=0.2), name="hidden_layer_1"))
model.add(Dropout(0.25, name="dropout_layer_1"))
model.add(Dense(128, activation=LeakyReLU(alpha=0.2), name="hidden_layer_2"))
model.add(Dropout(0.25, name="dropout_layer_2"))
model.add(Dense(64, activation=LeakyReLU(alpha=0.2), name="hidden_layer_3"))
model.add(Dropout(0.25, name="dropout_layer_3"))
model.add(Dense(output_shape, activation=Softmax(), name="output_layer"))


In [34]:
# compiling the model
adam = Adam(learning_rate=0.01)
model.compile(loss='categorical_crossentropy', optimizer=adam, metrics=["accuracy"])


In [35]:
print(model.summary())


Model: "Anuradha"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 hidden_layer_1 (Dense)      (None, 256)               35328     
                                                                 
 dropout_layer_1 (Dropout)   (None, 256)               0         
                                                                 
 hidden_layer_2 (Dense)      (None, 128)               32896     
                                                                 
 dropout_layer_2 (Dropout)   (None, 128)               0         
                                                                 
 hidden_layer_3 (Dense)      (None, 64)                8256      
                                                                 
 dropout_layer_3 (Dropout)   (None, 64)                0         
                                                                 
 output_layer (Dense)        (None, 54)                351

## Training the model

In [36]:
model.fit(x=train_X, y=train_y, epochs=200) # validation_split=0.2


Epoch 1/200
7/7 [==============================] - 0s 2ms/step - loss: 3.8669 - accuracy: 0.1010
Epoch 2/200
7/7 [==============================] - 0s 2ms/step - loss: 3.0506 - accuracy: 0.2067
Epoch 3/200
7/7 [==============================] - 0s 2ms/step - loss: 2.1807 - accuracy: 0.3558
Epoch 4/200
7/7 [==============================] - 0s 2ms/step - loss: 1.4644 - accuracy: 0.5817
Epoch 5/200
7/7 [==============================] - 0s 2ms/step - loss: 0.9647 - accuracy: 0.7115
Epoch 6/200
7/7 [==============================] - 0s 2ms/step - loss: 0.6637 - accuracy: 0.8125
Epoch 7/200
7/7 [==============================] - 0s 2ms/step - loss: 0.4964 - accuracy: 0.8317
Epoch 8/200
7/7 [==============================] - 0s 2ms/step - loss: 0.4901 - accuracy: 0.8413
Epoch 9/200
7/7 [==============================] - 0s 2ms/step - loss: 0.4230 - accuracy: 0.8558
Epoch 10/200
7/7 [==============================] - 0s 3ms/step - loss: 0.3156 - accuracy: 0.8798
Epoch 11/200
7/7 [===========

# Functions for getting results

In [37]:
def clean_text(text):
    """function to tokenize and then lemmatize and
    returning the tokens array"""
    tokens = word_tokenize(text)
    tokens = [lemmatizer.lemmatize(word) for word in tokens]
    return tokens


def bag_of_words(text, vocab):
    """function to get the bag of words and one hot
    encoding the words if they appear in the text and
    returning numpy array of bow"""
    tokens = clean_text(text)
    bow = [0] * len(vocab)
    for tok in tokens:
        for idx, word in enumerate(vocab):
            if word == tok:
                bow[idx] = 1
    return array(bow)


def pred_class(text, vocab, labels):
    """function to predict the class"""
    bow = bag_of_words(text, vocab)
    result = model.predict(array([bow]))[0]
    thresh = 0.2
    y_pred = [[idx, res] for idx, res in enumerate(result) if res > thresh]
    y_pred.sort(key=lambda x: x[1], reverse=True)
    return_list = []
    for res in y_pred:
        return_list.append(labels[res[0]])
    return return_list


def get_response(intents_list, intents_json):
    """taking the predicted class and returning
    a random response from the intents.json file"""
    tag = intents_list[0]
    list_of_intents = intents_json["intents"]
    for i in list_of_intents:
        if i["tag"] == tag:
            result = choice(i["responses"])
            break
    return result


## Testing the model

In [38]:
import platform
import pyttsx3
import speech_recognition as sr

engine = pyttsx3.init()
r = sr.Recognizer()
mic = sr.Microphone()

if platform.system() == "Windows":  # for Windows
    engine.setProperty(
        'voice', r"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech\Voices\Tokens\TTS_MS_EN-US_ZIRA_11.0")
elif platform.system() == "Darwin":  # for macOS
    engine.setProperty(
        'voice', "com.apple.speech.synthesis.voice.samantha")
else:
    pass

TEXT = "Anuradha is ready to chat! (say 'exit' to quit)"
print(TEXT)
engine.say(TEXT)
engine.runAndWait()

while True:
    with mic as source:
        r.adjust_for_ambient_noise(source)
        r.dynamic_energy_threshold = True
        print("Say Now")
        audio = r.record(source, duration=5)
    try:
        # message = r.recognize_google(audio, language="en-IN")
        message = input("You : ")
        print("You :", message)
        intents = pred_class(message, words, classes)
        result = get_response(intents, data)
        if message == 'exit':
            TEXT = "Bye! take care"
            break
        else:
            TEXT = result
    except sr.UnknownValueError:
        TEXT = "Sorry, I didn't get that"
    except sr.RequestError as e:
        TEXT = "Sorry, can't connect to the service"
    finally:
        try:
            print("Anuradha :", TEXT)
            engine.say(TEXT)
            engine.runAndWait()
        except NameError:
            pass


Anuradha is ready to chat! (say 'exit' to quit)
Say Now
You : who is the hod of cse department
1/1 [==============================] - 0s 51ms/step
Anuradha : Dr. Koushik Dasgupta sir is the H.O.D of Computer Science and Engineering Department.
Say Now
You : who is the hod of electrical engineering department
1/1 [==============================] - 0s 15ms/step
Anuradha : Mr. Shib Sankar Saha sir is the H.O.D of Electrical Engineering Department.
Say Now
You : who is the hod of ece department
1/1 [==============================] - 0s 18ms/step
Anuradha : Prof. Sukla Basu madam is the H.O.D of Electronics and Communication Engineering Department.
Say Now
You : what is the fees structure of btech cse
1/1 [==============================] - 0s 15ms/step
Anuradha : Dr. Koushik Dasgupta sir is the H.O.D of Computer Science and Engineering Department.
Say Now
You : what are the hostels in kgec
1/1 [==============================] - 0s 15ms/step
Anuradha : Acharya Prafulla Chandra Roy Hall, Rish